name: Docker Build and Push

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Login to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get the version and release notes
      if: github.event_name == 'release'
      run: |
        printf "RELEASE_VERSION=%s\n" "${{ github.event.release.tag_name }}" >> $GITHUB_ENV
        printf "RELEASE_NOTES<<EOF\n%s\nEOF\n" "${{ github.event.release.body }}" >> $GITHUB_ENV

    - name: Set version for manual dispatch
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "RELEASE_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        echo "RELEASE_NOTES=Manually triggered build" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          jason5ng32/myip:latest
          jason5ng32/myip:${{ env.RELEASE_VERSION }}
          ghcr.io/${{ github.repository_owner }}/myip:latest
          ghcr.io/${{ github.repository_owner }}/myip:${{ env.RELEASE_VERSION }}
        labels: |
          org.opencontainers.image.version=${{ env.RELEASE_VERSION }}
          org.opencontainers.image.description=${{ env.RELEASE_NOTES }}
        platforms: linux/amd64,linux/arm64
