name: Docker Build and Push

on:
  push:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 登录到 Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # 登录到 GitHub Packages
    - name: Login to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 从 release 事件获取版本号和日志
    - name: Get the version and release notes
      id: get_version
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        RELEASE_NOTES=$(gh release view ${{ env.RELEASE_VERSION }} --json body -q .body)
        echo "RELEASE_NOTES=${RELEASE_NOTES}" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          jason5ng32/myip:${{ env.RELEASE_VERSION }}
          ghcr.io/${{ github.repository_owner }}/myip:${{ env.RELEASE_VERSION }}
        labels: |
          org.opencontainers.image.version=${{ env.RELEASE_VERSION }}
          org.opencontainers.image.description=${{ env.RELEASE_NOTES }}
        platforms: linux/amd64,linux/arm64
